jeongju@jeongju-desktop:~/Desktop/MagToTheFuture$ /usr/bin/python3 /home/jeongju/Desktop/MagToTheFuture/MagToTheFuture/Hallsensors_with_MUX.py
[INFO] Starting GY-85 magnetometer polling loop...
[WARN] Sensor init error: [Errno 121] Remote I/O error
[WARN] Sensor init error: [Errno 121] Remote I/O error
[WARN] Sensor init error: [Errno 121] Remote I/O error
[WARN] Sensor init error: [Errno 121] Remote I/O error
[WARN] Sensor init error: [Errno 121] Remote I/O error
[WARN] Sensor init error: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/home/jeongju/Desktop/MagToTheFuture/MagToTheFuture/Hallsensors_with_MUX.py", line 46, in <module>
    select_mux_channel(mux_addr, channel)
  File "/home/jeongju/Desktop/MagToTheFuture/MagToTheFuture/Hallsensors_with_MUX.py", line 13, in select_mux_channel
    bus.write_byte(mux_addr, 1 << channe